openapi: 3.0.0
info:
  title: REST API for Library system
  description: REST API for Library system
  version: 1.0.0
  contact:
    email: example@gmail.com
    name: REST API example
tags:
  - name: library
    description: everything about books
servers:
  - url: http://localhost:5173/api/v1
paths:
  /books:
    get:
      tags:
        - library
      description: Use this API to fetch all books
      responses:
        "200":
          description: all books fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/book"
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddBook'
      responses:
        '201':
          description: The created book
  /books/{book_id}:
    get:
      tags:
        - library
      description: Use this API to fetch details of a course
      parameters:
        - name: book_id
          required: true
          in: path
          schema:
            type: integer
      responses:
        "200":
          description: course created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/book"
  /authors:
    get:
      summary: Get the list of all authors
      responses: 
        '200':
          description: list of all authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    post:
      summary: Add new author
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/AddAuthor'
      responses:
        '201':
        description: author added

components:
  schemas:
    book:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        id:
          type: integer
    books:
      type: array
      items:
        $ref: "#/components/schemas/book"
